POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3R1c2VyIiwiaWQiOiI2MjhlNGIxNGI4OTAzYjc5YWFiMmZhYjgiLCJpYXQiOjE2NTM0OTI5OTcsImV4cCI6MTY1MzQ5NjU5N30.CqKDYDI2p0GaPOowxBnx-mY5F64J1aqnMJhI2U5aF9w

{
	"title": "Test user blog2",
	"author": "Test user",
	"url": "http://www.google.com",
	"likes": 2
}